module.exports.places=[
    'Kootenai Health',
    'Kosciusko Community Hospital',
    'Kuakini Medical Center',
    'LARGO MEDICAL CENTER',
    'LDS Hospital',
    'LOMA LINDA UNIVERSITY MEDICAL CENTER-MURRIETA',
    'La Porte Hospital',
    'Labette Health',
    'Lafayette General Medical Center',
    'Lafayette General Orthopaedic Hospital',
    'Lahey Hospital and Medical Center',
    'Lake Charles Memorial Hospital',
    'Lake City Medical Center',
    'Lake Cumberland Regional Hospital',
    'Lake Granbury Medical Center',
    'Lake Health TriPoint Medical Center',
    'Lake Health West Medical Center',
    'Lake Huron Medical Center',
    'Lake Norman Regional Medical Center',
    'Lake Region Healthcare',
    'Lake Regional Health System',
    'Lakeland Community Hospital Niles',
    'Lakeland Regional Medical Center',
    'Lakeland Regional Medical Center-St. Joseph',
    'Lakes Region General Hospital',
    'Lakeview Hospital',
    'Lakeview Hospital',
    'Lakeview Regional Medical Center, a Campus of Tulane Medical Center',
    'Lakewood Ranch Medical Center',
    'Lakewood Regional Medical Center',
    'Lancaster General Hospital',
    'Landmark Medical Center',
    'Lane Regional Medical Center',
    'Lankenau Medical Center',
    'Laredo Medical Center',
    'Larkin Community Hospital',
    'Larkin Community Hospital - Palm Springs Campus',
    'Las Palmas Medical Center',
    'Latrobe Hospital',
    'Lawnwood Regional Medical Center & Heart Institute',
    'Lawrence & Memorial Hospital',
    'Lawrence General Hospital',
    'Lawrence Memorial Hospital',
    'LeConte Medical Center',
    'Lea Regional Medical Center',
    'Lee Memorial Hospital',
    'Legacy Good Samaritan Medical Center',
    'Legacy Meridian Park Medical Center',
    'Legacy Mount Hood Medical Center',
    'Legacy Salmon Creek Hospital',
    'Legacy Silverton Medical Center',
    'Lehigh Regional Medical Center',
    'Lehigh Valley Hospital - Cedar Crest',
    'Lehigh Valley Hospital - Hazleton',
    'Lehigh Valley Hospital - Pocono',
    'Lehigh Valley Hospital - Schuylkill',
    'Lenoir Memorial Hospital, Incorporated',
    'Lenox Hill Hospital',
    'Leonard J. Chabert Medical Center',
    'Leonard Morse Hospital',
    'LewisGale Hospital - Alleghany',
    'LewisGale Hospital - Montgomery',
    'LewisGale Hospital - Pulaski',
    'LewisGale Medical Center',
    'Lexington Medical Center',
    'Liberty Hospital',
    'Licking Memorial Hospital',
    'Lima Memorial Health System',
    'Logan Regional Hospital',
    'Logan Regional Medical Center',
    'Logansport Memorial Hospital',
    'Loma Linda University Medical Center',
    'Loma Linda University Medical Center East Campus',
    'Lompoc Valley Medical Center',
    'Lone Peak Hospital',
    'Lonesome Pine Hospital',
    'Long Beach Memorial Medical Center',
    'Long Island Jewish Forest Hills Hospital',
    'Long Island Jewish Medical Center',
    'Long Island Jewish Valley Stream',
    'Longview Regional Medical Center',
    'Los Alamitos Medical Center',
    'Los Angeles County - Harbor UCLA Medical Center',
    'Los Angeles County - Olive View UCLA Medical Center',
    'Los Angeles County University of Southern California Medical Center',
    'Los Robles Hospital and Medical Center',
    'Lourdes Hospital',
    'Lovelace Medical Center-Downtown',
    'Lovelace Regional Hospital - Roswell',
    'Lovelace Westside Hospital',
    'Lowell General Hospital - Saints Campus',
    'Lower Bucks Hospital',
    'Lower Keys Medical Center',
    'Loyola Gottlieb Memorial Hospital',
    'Loyola University Medical Center',
    'Lubbock Heritage Hospital LLC dba Grace Medical Center',
    'Lutheran Hospital of Indiana',
    'Lutheran Medical Center',
    'Lyndon Baines Johnson Hospital',
    'MH Mission Hospital McDowell, LLLP',
    'MHP Medical Center',
    'MORRISTOWN MEDICAL CENTER',
    'MUSC Health - Florence Medical Center',
    'MUSC Health - Lancaster Medical Center',
    'MUSC Health - Marion Medical Center',
    'MacNeal Hospital',
    'Mad River Community Hospital',
    'Madera Community Hospital',
    'Madison Memorial Hospital',
    'Magnolia Regional Health Center',
    'Maimonides Medical Center',
    'Maine Medical Center',
    'MaineGeneral Medical Center',
    'Mainehealth DBA Southern Maine Healthcare',
    'Manatee Memorial Hospital',
    'Maple Grove Hospital',
    'Margaret R. Pardee Memorial Hospital',
    'Maria Parham Health',
    'Marian Regional Medical Center',
    'Marietta Memorial Hospital',
    'MarinHealth Medical Center',
    'Marion General Hospital',
    'Marlborough Hospital',
    'Marshall Medical Center',
    'Marshall Medical Center North',
    'Marshall Medical Center South',
    'Marshfield Medical Center - Marshfield',
    'Marshfield Medical Center-Rice Lake',
    'Martin Luther King, Jr. Community Hospital',
    'Mary Greeley Medical Center',
    'Mary Rutan Hospital',
    'Mary Washington Hospital',
    'Massachusetts General Hospital',
    'Massena Memorial Hospital',
    'Mat-Su Regional Medical Center',
    'Matagorda Regional Medical Center',
    'Mather Hospital',
    'Maui Memorial Medical Center',
    'Maury Regional Hospital',
    'Mayo Clinic Health System - Austin',
    'Mayo Clinic Health System - Franciscan Healthcare in LaCrosse',
    'Mayo Clinic Health System - Mankato Hospital',
    'Mayo Clinic Health System In Red Wing',
    'Mayo Clinic Health System in Eau Claire',
    'Mayo Clinic Hospital',
    'Mayo Clinic Hospital',
    'Mayo Clinic Hospital - Methodist Campus',
    'Mayo Clinic Hospital - Saint Marys Campus',
    'McAlester Regional Health Center',
    'McCullough-Hyde Memorial Hospital',
    'McDonough District Hospital',
    'McKay-Dee Hospital',
    'McKee Medical Center',
    'McKenzie - Willamette Medical Center',
    'McLaren - Bay Region',
    'McLaren - Lapeer Region',
    'McLaren - Northern Michigan',
    'McLaren - Oakland',
    'McLaren Central Michigan',
    'McLaren Flint',
    'McLaren Macomb',
    'McLaren Port Huron',
    'McLeod Health Cheraw',
    'McLeod Health Clarendon',
    'McLeod Loris',
    'McLeod Regional Medical Center of the Pee Dee',
    'McLeod Seacoast',
    'Meadows Regional Medical Center',
    'Meadville Medical Center',
    'Mease Countryside Hospital',
    'Mease Dunedin Hospital',
    'MedStar Franklin Square Medical Center',
    'MedStar Georgetown University Hospital',
    'MedStar Good Samaritan Hospital',
    'MedStar Harbor Hospital',
    'MedStar Montgomery Medical Center',
    'MedStar Southern Maryland Hospital Center',
    'MedStar Washington Hospital Center',
    'Medical Center Enterprise',
    'Medical Center Hospital',
    'Medical Center at Bowling Green',
    'Medical Center of Aurora',
    'Medical Center of South Arkansas',
    'Medical Center of Trinity',
    'Medical City Alliance',
    'Medical City Arlington',
    'Medical City Dallas',
    'Medical City Denton',
    'Medical City Fort Worth',
    'Medical City Frisco',
    'Medical City Las Colinas',
    'Medical City Lewisville',
    'Medical City McKinney',
    'Medical City North Hills',
    'Medical City Plano',
    'Medical City Weatherford',
    'Medical University of South Carolina University Medical Center',
    'Medical West Hospital Authority, an Affiliate of UAB Health System',
    'Melbourne Regional Medical Center',
    'Melrose-Wakefield Hospital',
    'Memorial Health University Medical Center',
    'Memorial Healthcare',
    'Memorial Hermann - Texas Medical Center',
    'Memorial Hermann Cypress Hospital',
    'Memorial Hermann Greater Heights Hospital',
    'Memorial Hermann Katy Hospital',
    'Memorial Hermann Memorial City Medical Center',
    'Memorial Hermann Northeast',
    'Memorial Hermann Pearland Hospital',
    'Memorial Hermann Southeast',
    'Memorial Hermann Southwest Hospital',
    'Memorial Hermann Sugar Land Hospital',
    'Memorial Hermann The Woodlands Hospital',
    'Memorial Hixson Hospital',
    'Memorial Hospital',
    'Memorial Hospital Chattanooga',
    'Memorial Hospital East',
    'Memorial Hospital Jacksonville',
    'Memorial Hospital Miramar',
    'Memorial Hospital Pembroke',
    'Memorial Hospital West',
    'Memorial Hospital and Health Care Center',
    'Memorial Hospital at Gulfport',
    'Memorial Hospital of Carbondale',
    'Memorial Hospital of South Bend',
    'Memorial Hospital of Tampa',
    'Memorial Medical Center',
    'Memorial Medical Center',
    'Memorial Regional Hospital',
    'Memorial Regional Hospital South',
    'Memorial Satilla Health',
    'MemorialCare Orange Coast Medical Center',
    'MemorialCare Saddleback Medical Center',
    'Menifee Valley Medical Center',
    'Menorah Medical Center',
    'Mercer County Community Hospital- Coldwater',
    'Mercy Fitzgerald Hospital',
    'Mercy General Hospital',
    'Mercy Gilbert Medical Center',
    'Mercy Health - St. Vincent Medical Center',
    'Mercy Health - Anderson Hospital',
    'Mercy Health - Clermont Hospital',
    'Mercy Health - Fairfield Hospital',
    'Mercy Health - Lorain Hospital',
    'Mercy Health - Springfield Regional Medical Center',
    'Mercy Health - St. Anne Hospital',
    'Mercy Health - St. Charles Hospital',
    'Mercy Health - West Hospital',
    'Mercy Health Lourdes',
    'Mercy Health Mercy Campus',
    'Mercy Hospital - Coon Rapids',
    'Mercy Hospital - Downtown',
    'Mercy Hospital - Southwest',
    'Mercy Hospital - Unity Campus',
    'Mercy Hospital Ada',
    'Mercy Hospital Ardmore',
    'Mercy Hospital Fort Smith',
    'Mercy Hospital Jefferson',
    'Mercy Hospital Joplin',
    'Mercy Hospital Lebanon',
    'Mercy Hospital Northwest Arkansas',
    'Mercy Hospital Oklahoma City',
    'Mercy Hospital South',
    'Mercy Hospital Springfield',
    'Mercy Hospital St. Louis',
    'Mercy Hospital Washington',
    'Mercy Hospital and Medical Center',
    'Mercy Hospital of Folsom',
    'Mercy Hospital of Iowa City',
    'Mercy Medical Center',
    'Mercy Medical Center',
    'Mercy Medical Center',
    'Mercy Medical Center',
    'Mercy Medical Center',
    'Mercy Medical Center of Redding',
    'Mercy Medical Center of Springfield',
    'Mercy Philadelphia Hospital',
    'Mercy Regional Medical Center',
    'Mercy San Juan Medical Center',
    'MercyOne Cedar Falls Medical Center',
    'MercyOne Clinton Medical Center - North Campus',
    'MercyOne Des Moines Medical Center',
    'MercyOne Dubuque Medical Center',
    'MercyOne North Iowa Medical Center',
    'MercyOne Siouxland Medical Center',
    'MercyOne Waterloo Medical Center',
    'MercyOne West Des Moines Medical Center',
    'Mercyhealth Hospital and Trauma Center - Janesville',
    'Merit Health Biloxi',
    'Merit Health Central',
    'Merit Health Natchez',
    'Merit Health Rankin',
    'Merit Health River Oaks',
    'Merit Health River Region',
    'Merit Health Wesley',
    'Meritus Medical Center',
    'Methodist Charlton Medical Center',
    'Methodist Dallas Medical Center',
    'Methodist Fremont Health',
    'Methodist Hospital',
    'Methodist Hospital',
    'Methodist Hospital South',
    'Methodist Hospital of Sacramento',
    'Methodist Hospital of Southern California',
    'Methodist Hospitals - Northlake Campus',
    'Methodist Hospitals - Southlake Campus',
    'Methodist Jennie Edmundson Hospital',
    'Methodist Le Bonheur Germantown Hospital',
    'Methodist Mansfield Medical Center',
    'Methodist Medical Center of Oak Ridge',
    'Methodist North Hospital',
    'Methodist Olive Branch Hospital',
    'Methodist Richardson Medical Center',
    'Methodist South Hospital',
    'Methodist Specialty & Transplant Hospital',
    'Methodist Stone Oak Hospital',
    'Methodist Texsan Hospital',
    'Methodist University Hospital',
    'Methodist West Hospital',
    'Metro Health - University of MI Health',
    'MetroHealth Medical Center',
    'Metropolitan Methodist Hospital',
    'Metrowest Medical Center',
    'Miami Valley Hospital',
    'Michigan Medicine',
    'Mid Coast Hospital',
    'Mid-Columbia Medical Center',
    'MidHudson Regional Hospital of Westchester Medical Center',
    'MidMichigan Medical Center - Alpena',
    'MidMichigan Medical Center - West Branch',
    'MidMichigan Medical Center-Gratiot',
    'MidMichigan Medical Center-Midland',
    'MidState Medical Center',
    'Middlesex Hospital',
    'Midland Memorial Hospital',
    'Milford Regional Medical Center',
    'Millard Fillmore Suburban Hospital',
    'Mills-Peninsula Health Services',
    'Minden Medical Center',
    'Mission Community Hospital',
    'Mission Hospital',
    'Mission Hospital Laguna Beach',
    'Mission Hospital Regional Medical Center',
    'Mission Regional Medical Center',
    'Mission Trail Baptist Hospital',
    'Mississippi Baptist Medical Center',
    'Missouri Baptist Medical Center',
    'Missouri Delta Medical Center',
    'Mizell Memorial Hospital',
    'Mobile Infirmary Medical Center',
    'Mon Health Medical Center',
    'Monmouth Medical Center',
    'Monmouth Medical Center Southern Campus',
    'Monongahela Valley Hospital',
    'Monroe Clinic Hospital',
    'Montclair Hospital Medical Center',
    'Montefiore Einstein Campus',
    'Montefiore Moses Campus',
    'Montefiore New Rochelle Hospital',
    'Montefiore Nyack Hospital',
    'Montrose Memorial Hospital',
    'Monument Health Rapid City Hospital',
    'Morris Hospital',
    'Morristown-Hamblen Healthcare System',
    'Morton Hospital',
    'Morton Plant Hospital',
    'Morton Plant North Bay Hospital',
    'Mosaic Life Care at St Joseph - Medical Center',
    'Moses Taylor Hospital',
    'Mount Auburn Hospital',
    'Mount Carmel East Hospital',
    'Mount Carmel Grove City',
    'Mount Pleasant Hospital',
    'Mount Sinai Beth Israel',
    'Mount Sinai Brooklyn',
    'Mount Sinai Medical Center',
    'Mount Sinai Morningside',
    'Mount Sinai Queens',
    'Mount Sinai West',
    'Mountain Point Medical Center',
    'Mountain View Hospital',
    'Mountain View Regional Hospital',
    'Mountain Vista Medical Center',
    'Mountainview Hospital',
    'Mountainview Regional Medical Center',
    'Mt. Graham Regional Medical Center',
    'Mt. Sinai Hospital',
    'MultiCare Allenmore Hospital',
    'MultiCare Auburn Medical Center',
    'MultiCare Deaconess Hospital',
    'MultiCare Valley Hospital',
    'Multicare Good Samaritan Hospital',
    'Munson Healthcare Cadillac Hospital',
    'Munson Healthcare Grayling Hospital',
    'Munson Healthcare Manistee Hospital',
    'Munson Medical Center',
    'Murray-Calloway County Hospital',
    'NCH Baker Hospital',
    'NCH North Naples Hospital',
    'NEA Baptist Memorial Hospital',
    'NORTHERN REGIONAL HOSPITAL',
    'NORTHSIDE HOSPITAL',
    'NORTON HOSPITAL',
    'NYC Health Hospitals - Metropolitan',
    'NYC Health Hospitals - Queens',
    'NYC Health & Hospitals - Harlem',
    'NYC Health and Hospitals - Bellevue',
    'NYC Health and Hospitals - Lincoln',
    'NYC Health and Hospitals - Woodhull',
    'NYC Health and Hospitals Elmhurst',
    'NYC Health and Hospitals Jacobi',
    'NYC Health and Hospitals Kings County',
    'NYC Health and Hospitals North Central Bronx',
    'NYU Langone Hospital - Brooklyn',
    'NYU Langone Hospitals',
    'NYU Langone Hospital—Long Island',
    'Nacogdoches Medical Center',
    'Nacogdoches Memorial Hospital',
    'Nash Hospitals, Inc.',
    'Nashville General Hospital',
    'Nassau University Medical Center',
    'Natchitoches Regional Medical Center',
    'Nathan Littauer Hospital and Nursing Home',
    'National Park Medical Center',
    'Natividad Medical Center',
    'Navarro Regional Hospital',
    'Navicent Health Baldwin',
    'Nazareth Hospital',
    'Nebraska Medical Center',
    'New Hanover Regional Medical Center',
    'New York - Presbyterian Brooklyn Methodist Hospital',
    'New York-Presbyterian Hospital Columbia University Medical Center',
    'New York-Presbyterian Hudson Valley Hospital',
    'New York-Presbyterian Lawrence Hospital',
    'New York-Presbyterian The Allen Hospital',
    'New York-Presbyterian, Lower Manhattan Hospital',
    'New York-Presbyterian/Weill Cornell Medical Center',
    'Newark Beth Israel Medical Center',
    'Newark-Wayne Community Hospital',
    'Newberry County Memorial Hospital',
    'Newport Hospital',
    'Newton Medical Center',
    'Newton Medical Center',
    'Newton-Wellesley Hospital',
    'Norman Regional Health System - Healthplex',
    'Norman Regional Hospital - Porter Campus',
    'North Alabama Medical Center',
    'North Arkansas Regional Medical Center',
    'North Baldwin Infirmary',
    'North Central Baptist Hospital',
    'North Colorado Medical Center',
    'North Florida Regional Medical Center',
    'North Fulton Hospital',
    'North Hawaii Community Hospital',
    'North Hospital',
    'North Kansas City Hospital',
    'North Knoxville Medical Center',
    'North Memorial Health Hospital',
    'North Mississippi Medical Center - Tupelo',
    'North Mississippi Medical Center - West Point',
    'North Mississippi Medical Center Gilmore-Amory',
    'North Oaks Medical Center',
    'North Okaloosa Medical Center',
    'North Shore Medical Center',
    'North Shore Medical Center',
    'North Shore University Hospital',
    'North Suburban Medical Center',
    'North Texas Medical Center',
    'North Vista Hospital',
    'NorthBay Medical Center',
    'NorthBay VacaValley Hospital',
    'NorthShore University HealthSystem -Evanston Hospital',
    'NorthShore University HealthSystem -Glenbrook Hospital',
    'NorthShore University HealthSystem-Highland Park Hospital',
    'Northcrest Medical Center',
    'Northeast Baptist Hospital',
    'Northeast Georgia Medical Center',
    'Northeast Methodist Hospital',
    'Northeast Regional Medical Center',
    'Northeastern Health System Tahlequah',
    'Northeastern Nevada Regional Hospital',
    'Northern Dutchess Hospital',
    'Northern Light A.R. Gould Hospital',
    'Northern Light Eastern Maine Medical Center',
    'Northern Light Health Mercy Hospital',
    'Northern Light Inland Hospital',
    'Northern Light Maine Coast Hospital',
    'Northern Louisiana Medical Center',
    'Northern Nevada Medical Center',
    'Northern Westchester Hospital',
    'Northport Medical Center',
    'Northridge Hospital Medical Center-Roscoe Boulevard Campus',
    'Northside Hospital Atlanta',
    'Northside Hospital Cherokee',
    'Northside Hospital Forsyth',
    'Northwest Community Hospital',
    'Northwest Hospital',
    'Northwest Medical Center',
    'Northwest Medical Center',
    'Northwest Medical Center',
    'Northwest Medical Center Bentonville',
    'Northwest Mississippi Medical Center',
    'Northwest Texas Healthcare System',
    'Northwestern Medicine Central DuPage Hospital',
    'Northwestern Medicine Delnor Hospital',
    'Northwestern Medicine Huntley Hospital',
    'Northwestern Medicine Kishwaukee Hospital',
    'Northwestern Medicine McHenry Hospital',
    'Northwestern Medicine, Lake Forest Hospital',
    'Northwestern Memorial Hospital',
    'Norton Audubon Hospital',
    'Norton Brownsboro Hospital',
    'Norton Community Hospital',
    'Norwalk Hospital',
    'Norwegian American Hospital',
    'Novant Health Brunswick Medical Center',
    'Novant Health Forsyth Medical Center',
    'Novant Health Huntersville Medical Center',
    'Novant Health Kernersville Medical Center',
    'Novant Health Matthews Medical Center',
    'Novant Health Medical Park Hospital',
    'Novant Health Presbyterian Medical Center',
    'Novant Health Rowan Medical Center',
    'Novant Health Thomasville Medical Center',
    'Novant Health UVA Health System Culpeper Medical Center',
    'Novant Health UVA Health System Haymarket Medical Center',
    'Novant Health UVA Health System Prince William Medical Center',
    'Novato Community Hospital',
    'Noyes Memorial Hospital',
    'OHSU - Marquam Hill Campus',
    'ONSLOW MEMORIAL HOSPITAL',
    'OSF HealthCare Saint Francis Medical Center',
    'OSF HealthCare System dba OSF Little Co of Mary Medical Center',
    'OSF Heart of Mary Medical Center',
    'OSF Sacred Heart Medical Center',
    'OSF St. Mary Medical Center',
    'OU Medical Center',
    'OU Medical Center Edmond',
    'Oak Hill Hospital',
    'Oakbend Medical Center - Jackson Street Campus',
    'Oakbend Medical Center - Williams Way Campus',
    'Ocala Regional Medical Center',
    'Ocean Medical Center',
    'Ocean Springs Hospital',
    'Ochsner Baptist Medical Center',
    'Ochsner LSU Health Shreveport',
    'Ochsner LSU Health Shreveport',
    'Ochsner Medical Center - Kenner',
    'Ochsner Medical Center - New Orleans',
    'Ochsner Medical Center - North Shore',
    'Ochsner Medical Center - West Bank',
    'Ochsner Medical Center Hancock',
    'Ochsner Medical Center-Baton Rouge',
    'Ochsner St. Mary',
    'Odessa Regional Medical Center',
    'Ogden Regional Medical Center',
    'Ohio Health - Marion General Hospital',
    'Ohio Valley General Hospital',
    'OhioHealth Doctors Hospital',
    'OhioHealth Dublin Methodist Hospital',
    'OhioHealth Grady Memorial Hospital',
    'OhioHealth Grant Medical Center',
    'OhioHealth Mansfield Hospital',
    'OhioHealth Riverside Methodist Hospital',
    'Olathe Medical Center',
    'Olean General Hospital',
    'Olympic Medical Center',
    'Oneida Healthcare',
    'Opelousas General Health System',
    'Orange County Global Medical Center',
    'Orange Park Medical Center',
    'Orlando Health South Lake Hospital',
    'Orlando Health Dr. P. Phillips Hospital',
    'Orlando Health Health Central Hospital',
    'Orlando Health South Seminole Hospital',
    'Orlando Health St. Cloud Hospital',
    'Orlando Health- Orlando Regional Medical Center',
    'Oro Valley Hospital',
    'Osborn Medical Center',
    'Osceola Regional Medical Center',
    'Oswego Hospital',
    'Otsego Memorial Hospital',
    'Ottawa Regional Hospital and Healthcare Center dba OSF Saint Elizabeth Medical Center',
    'Ottumwa Regional Health Center',
    'Ouachita County Medical Center',
    'Our Lady of Lourdes Regional Medical Center',
    'Our Lady of The Lake Regional Medical Center',
    'Our Lady of the Lake Ascension',
    'Overlake Hospital Medical Center',
    'Overland Park Regional Medical Center',
    'Overlook Medical Center',
    'Oviedo Medical Center',
    'Owensboro Health',
    'Ozarks Medical Center',
    'PIH Good Samaritan Hospital of Los Angeles',
    'PIH Health Hospital - Downey',
    'PIH Health Hospital - Whittier',
    'Palestine Regional Medical Center-East',
    'Pali Momi Medical Center',
    'Palm Bay Hospital',
    'Palm Beach Gardens Medical Center',
    'Palmdale Regional Medical Center',
    'Palmetto General Hospital',
    'Palms West Hospital',
    'Palms of Pasadena Hospital',
    'Palo Pinto General Hospital',
    'Palomar Medical Center',
    'Palos Community Hospital',
    'Pampa Regional Medical Center',
    'Paoli Hospital',
    'Paradise Valley Hospital',
    'Park Nicollet Methodist Hospital',
    'Parkland Health & Hospital System',
    'Parkland Health Center of Farmington',
    'Parkland Medical Center',
    'Parkridge East Hospital',
    'Parkridge Medical Center',
    'Parkview Community Hospital Medical Center',
    'Parkview Medical Center',
    'Parkview Regional Medical Center',
    'Parkwest Medical Center',
    'Parrish Medical Center',
    'Passavant Area Hospital',
    'PeaceHealth Sacred Heart Medical Center at RiverBend',
    'PeaceHealth Southwest Medical Center',
    'PeaceHealth St. John Medical Center',
    'PeaceHealth St. Joseph Medical Center',
    'Peconic Bay Medical Center',
    'Pelham Medical Center',
    'Pen Bay Medical Center',
    'Penn Highlands DuBois',
    'Penn Highlands Huntingdon',
    'Penn Medicine Princeton Medical Center',
    'Penn Presbyterian Medical Center',
    'Penn State Health Holy Spirit Medical Center',
    'Penn State Milton S. Hershey Medical Center',
    'Pennsylvania Hospital',
    'Petaluma Valley Hospital',
    'Peterson Regional Medical Center',
    'Phelps Health',
    'Phelps Hospital',
    'Phoebe Putney Memorial Hospital',
    'Phoebe Sumter Medical Center',
    'Phoenixville Hospital',
    'Physicians Regional Medical Center - Collier Boulevard',
    'Physicians Regional Medical Center - Pine Ridge',
    'Piedmont Athens Regional Medical Center',
    'Piedmont Columbus Regional Midtown',
    'Piedmont Columbus Regional Northside',
    'Piedmont Fayette Hospital',
    'Piedmont Henry Hospital',
    'Piedmont Hospital',
    'Piedmont Medical Center',
    'Piedmont Mountainside Hospital',
    'Piedmont Newnan Hospital',
    'Piedmont Newton Hospital',
    'Piedmont Rockdale Hospital',
    'Piedmont Walton',
    'Pikeville Medical Center',
    'Pioneers Memorial Hospital',
    'Placentia-Linda Hospital',
    'Plains Regional Medical Center',
    'Plainview Hospital',
    'Plantation General Hospital',
    'Platte Valley Medical Center',
    'Pleasant Valley Hospital',
    'Poinciana Medical Center',
    'Pomerado Hospital',
    'Pomona Valley Hospital Medical Center',
    'Poplar Bluff RMC - Oak Grove',
    'Porter Regional Hospital',
    'Portneuf Medical Center',
    'Portsmouth Regional Hospital',
    'Pottstown Hospital',
    'Prairie Lakes Healthcare System',
    'Pratt Regional Medical Center',
    'Presbyterian Espanola Hospital',
    'Presbyterian Hospital',
    'Princeton Community Hospital',
    'Prisma Health Baptist',
    'Prisma Health Baptist Easley Hospital',
    'Prisma Health Baptist Parkridge',
    'Prisma Health Greenville Memorial Hospital',
    'Prisma Health Greer Memorial Hospital',
    'Prisma Health Hillcrest Hospital',
    'Prisma Health Laurens County Hospital',
    'Prisma Health Oconee Memorial Hospital',
    'Prisma Health Richland',
    'Prisma Health Tuomey Hospital',
    'ProHealth Oconomowoc Memorial Hospital',
    'ProHealth Waukesha Memorial Hospital',
    'ProMedica Bay Park Hospital',
    'ProMedica Bixby Hospital',
    'ProMedica Flower Hospital',
    'ProMedica Memorial Hospital',
    'ProMedica Monroe Regional Hospital',
    'Progress West Hospital',
    'Promedica Toledo Hospital',
    'Providence Alaska Medical Center',
    'Providence Centralia Hospital',
    'Providence Health',
    'Providence Holy Cross Medical Center',
    'Providence Holy Family Hospital',
    'Providence Hospital',
    'Providence Little Company of Mary Medical Center San Pedro',
    'Providence Little Company of Mary Medical Center Torrance',
    'Providence Medford Medical Center',
    'Providence Medical Center',
    'Providence Milwaukie Hospital',
    'Providence Newberg Medical Center',
    'Providence Portland Medical Center',
    'Providence Regional Medical Center Everett',
    'Providence St. Mary Medical Center',
    'Providence St. Patrick Hospital',
    'Providence St. Peter Hospital',
    'Providence St. Vincent Medical Center',
    'Providence Tarzana Medical Center',
    'Providence Willamette Falls Medical Center',
    'Putnam Community Medical Center',
    'Putnam Hospital Center',
    'Queen of the Valley Medical Center',
    'RCHP Billings-Missoula LLC DBA Community Medical Center',
    'REGIONAL MEDICAL CENTER BAYONET POINT',
    'RMC Anniston',
    'Raleigh General Hospital',
    'Rancho Springs Medical Center',
    'Randolph Health',
    'Rapides Regional Medical Center',
    'Raritan Bay Medical Center of Old Bridge',
    'Raritan Bay Medical Center of Perth Amboy',
    'Raulerson Hospital',
    'Reading Hospital',
    'Redlands Community Hospital',
    'Redmond Regional Medical Center',
    'Regional Hospital of Scranton',
    'Regional Medical Center',
    'Regional Medical Center of Orangeburg and Calhoun Counties',
    'Regional Medical Center of San Jose',
    'Regional West Medical Center',
    'Regions Hospital',
    'Reid Health',
    'Renown Regional Medical Center',
    'Renown South Meadows Medical Center',
    'Research Medical Center Main Campus',
    'Resolute Health Hospital',
    'Reynolds Memorial Hospital',
    'Rhode Island Hospital',
    'Rice Memorial Hospital',
    'Richmond University Medical Center',
    'Riddle Hospital',
    'Ridgeview Medical Center',
    'Rio Grande Regional Hospital',
    'Riverside Community Hospital',
    'Riverside Regional Medical Center',
    'Riverside Tappahannock Hospital',
    'Riverside University Health System - Medical Center',
    'Riverside Walter Reed Hospital',
    'Riverton Hospital',
    'Riverview Hospital',
    'Riverview Medical Center',
    'Riverview Regional Medical Center',
    'Roane Medical Center',
    'Robert Wood Johnson University Hospital',
    'Robert Wood Johnson University Hospital Rahway',
    'Robert Wood Johnson University Hospital Somerset',
    'Robert Wood Johnson University Hospital at Hamilton',
    'Rochester General Hospital',
    'Rockledge Regional Medical Center',
    'Rome Memorial Hospital',
    'Roper Hospital',
    'Rose Medical Center',
    'Rush Copley Medical Center',
    'Rush Foundation Hospital',
    'Rush Oak Park Hospital',
    'Rush University Medical Center',
    'Russell Medical Center',
    'Rutherford Regional Medical Center',
    'Rutland Regional Medical Center',
    'SHEA MEDICAL CENTER',
    'SOUTH BAY HOSPITAL',
    'SSM Health DePaul Hospital-St. Louis',
    'SSM Health Good Samaritan Hospital - Mount Vernon',
    'SSM Health Saint Louis University Hospital',
    'SSM Health St. Anthony Hospital-Oklahoma City',
    'SSM Health St. Clare Hospital - Baraboo',
    'SSM Health St. Clare Hospital - St. Louis',
    'SSM Health St. Joseph Hospital - Lake St. Louis',
    'SSM Health St. Joseph Hospital-St. Charles',
    'SUNY Upstate Medical University Hospital',
    'Sacred Heart Hospital On The Emerald Coast',
    'SageWest Health Care - Lander',
    'SageWest Health Care - Riverton',
    'Saint Agnes Medical Center',
    'Saint Alphonsus Medical Center - Nampa',
    'Saint Alphonsus Medical Center - Ontario',
    'Saint Alphonsus Regional Medical Center - Boise',
    'Saint Francis Hospital',
    'Saint Francis Hospital - Bartlett',
    'Saint Francis Hospital -Memphis',
    'Saint Francis Hospital Muskogee',
    'Saint Francis Hospital South',
    'Saint Francis Medical Center',
    'Saint Francis Memorial Hospital',
    'Saint Joseph - London',
    'Saint Joseph East',
    'Saint Joseph Health Mishawaka Medical Center',
    'Saint Joseph Health Plymouth Medical Center',
    'Saint Joseph Hospital',
    'Saint Joseph Hospital',
    'Salem Medical Center',
    'Salina Regional Health Center',
    'Salinas Valley Memorial Healthcare System',
    'Saline Memorial Hospital',
    'Salt Lake Regional Medical Center',
    'Samaritan Albany General Hospital',
    'Samaritan Hospital',
    'Samaritan Hospital - Main Campus',
    'Samaritan Medical Center',
    'Sampson Regional Medical Center',
    'San Angelo Community Medical Center',
    'San Antonio Regional Hospital',
    'San Dimas Community Hospital',
    'San Gabriel Valley Medical Center',
    'San Gorgonio Memorial Hospital',
    'San Joaquin General Hospital',
    'San Juan Regional Medical Center',
    'San Leandro Hospital',
    'San Mateo Medical Center',
    'San Ramon Regional Medical Center',
    'Sanford Aberdeen Medical Center',
    'Sanford Bemidji Medical Center',
    'Sanford Broadway Medical Center',
    'Sanford Medical Center - Bismarck',
    'Sanford Medical Center Fargo',
    'Sanford USD Medical Center',
    'Santa Barbara Cottage Hospital',
    'Santa Clara Valley Medical Center',
    'Santa Rosa Medical Center',
    'Santa Rosa Memorial Hospital',
    'Sarah Bush Lincoln Health Center',
    'Sarasota Memorial Hospital',
    'Saratoga Hospital',
    'Scenic Mountain Medical Center',
    'Schneck Medical Center',
    'Scotland Health Care System',
    'Scripps Green Hospital',
    'Scripps Memorial Hospital of Encinitas',
    'Scripps Memorial Hospital of La Jolla',
    'Scripps Mercy Hospital of Chula Vista',
    'Scripps Mercy Hospital of San Diego',
    'Sebastian River Medical Center',
    'Self Regional Healthcare',
    'Sentara Albemarle Medical Center',
    'Sentara CarePlex Hospital',
    'Sentara Halifax Regional Hospital',
    'Sentara Leigh Hospital',
    'Sentara Martha Jefferson Hospital',
    'Sentara Norfolk General Hospital',
    'Sentara Northern Virginia Medical Center',
    'Sentara Obici Hospital',
    'Sentara Princess Anne Hospital',
    'Sentara RMH Medical Center',
    'Sentara Virginia Beach General Hospital',
    'Sentara Williamsburg Regional Medical Center',
    'Sequoia Hospital',
    'Seton Medical Center',
    'Seton Medical Center Harker Heights',
    'Shannon Medical Center',
    'Sharon Hospital',
    'Sharon Regional Medical Center',
    'Sharp Chula Vista Medical Center',
    'Sharp Coronado Hospital and Healthcare Center',
    'Sharp Grossmont Hospital',
    'Sharp Memorial Hospital',
    'Shasta Regional Medical Center',
    'Shelby Baptist Medical Center',
    'Sherman Oaks Hospital',
    'Shore Medical Center',
    'Sibley Memorial Hospital',
    'Sierra Nevada Memorial Hospital',
    'Sierra View Medical Center',
    'Sierra Vista Regional Medical Center',
    'Signature Healthcare Brockton Hospital',
    'Silver Cross Hospital',
    'Sinai Hospital of Baltimore',
    'Sinai-Grace Hospital',
    'Singing River Gulfport',
    'Singing River Hospital',
    'Skagit Valley Hospital',
    'Sky Lakes Medical Center',
    'Sky Ridge Medical Center',
    'Slidell Memorial Hospital',
    'South Baldwin Regional Medical Center',
    'South Central Regional Medical Center',
    'South County Hospital',
    'South Florida Baptist Hospital',
    'South Georgia Medical Center',
    'South Nassau Communities Hospital',
    'South Shore Hospital',
    'South Texas Health System Edinburg',
    'South Texas Health System Heart',
    'South Texas Health System McAllen',
    'Southampton Hospital',
    'Southampton Memorial Hospital',
    'Southeast Georgia Health System - Brunswick Campus',
    'Southeast Georgia Health System - Camden Campus',
    'Southeast Health Medical Center',
    'Southeast Hospital',
    'Southeastern Ohio Regional Medical Center',
    'Southeastern Regional Medical Center',
    'Southern Hills Hospital and Medical Center',
    'Southern New Hampshire Medical Center',
    'Southern Ocean Medical Center',
    'Southern Ohio Medical Center',
    'Southern Regional Medical Center',
    'Southern Tennessee Regional Health System Sewanee',
    'Southern Tennessee Regional Health System Winchester',
    'Southside Hospital',
    'Southside Regional Medical Center',
    'Southwest General Health Center',
    'Southwest General Hospital',
    'Southwest Medical Center',
    'Southwest Mississippi Regional Medical Center',
    'Southwestern Medical Center',
    'Southwestern Vermont Medical Center',
    'Sovah Health Martinsville',
    'Sparrow Hospital & Health System',
    'Spartanburg Medical Center',
    'Spartanburg Medical Center - Mary Black Campus',
    'Spectrum Health Big Rapids Hospital',
    'Spectrum Health Blodgett Hospital',
    'Spectrum Health Butterworth Hospital',
    'Spectrum Health Ludington Hospital',
    'Spectrum Health United Hospital',
    'Spectrum Health Zeeland Community Hospital',
    'Spencer Hospital',
    'Spotsylvania Regional Medical Center',
    'Spring Valley Hospital Medical Center',
    'Springfield Hospital',
    'St Mary Medical Center',
    'St Mary Medical Center',
    'St Vincent Hospital',
    'St. Agnes Hospital',
    'St. Agnes Hospital',
    'St. Alexius Hospital - Broadway Campus',
    'St. Anne Hospital',
    'St. Anthony Hospital',
    'St. Anthony Regional Hospital',
    'St. Anthony Shawnee Hospital',
    'St. Bernards Medical Center',
    'St. Catherine of Siena Medical Center',
    'St. Charles Health System - Bend',
    'St. Charles Health System - Redmond',
    'St. Charles Hospital',
    'St. Clair Hospital',
    'St. Claire Regional Medical Center',
    'St. Clare Hospital',
    'St. Cloud Hospital',
    'St. Elizabeth Boardman Hospital',
    'St. Elizabeth Community Hospital',
    'St. Elizabeth Dearborn',
    'St. Elizabeth Healthcare - Edgewood',
    'St. Elizabeth Healthcare - Florence',
    'St. Elizabeth Healthcare - Ft. Thomas',
    'St. Elizabeth Medical Center',
    'St. Elizabeth Youngstown Hospital',
    'St. Francis Hospital & Medical Center',
    'St. Francis Hospital - Downtown',
    'St. Francis Hospital of Federal Way',
    'St. Francis Hospital, The Heart Center',
    'St. Francis Medical Center',
    'St. Francis Medical Center of Trenton',
    'St. Francis Regional Medical Center',
    'St. Francis- Emory Healthcare',
    'St. James Healthcare',
    'St. Joseph Hospital of Bangor',
    'St. Joseph Hospital of Eureka',
    'St. Joseph Hospital of Fort Wayne',
    'St. Joseph Hospital of Nashua',
    'St. Joseph Hospital of Orange',
    'St. Joseph Medical Center',
    'St. Joseph Medical Center',
    'St. Joseph Medical Center of Tacoma',
    'St. Joseph Mercy - Chelsea',
    'St. Joseph Mercy Hospital, Ann Arbor',
    'St. Joseph Mercy Livingston Hospital',
    'St. Joseph Mercy Oakland',
    'St. Joseph Regional Medical Center',
    'St. Joseph Warren Hospital',
    'St. Louise Regional Hospital',
    'St. Lucie Medical Center',
    'St. Mary Medical Center of Long Beach',
    'St. Mary Mercy Hospital',
    'St. Petersburg General Hospital',
    'St. Tammany Health System',
    'St. Vincent Carmel Hospital',
    'St. Vincent Charity Medical Center',
    'St. Vincent Healthcare',
    'St. Vincent Indianapolis Hospital',
    'St. Vincent Kokomo',
    'Stamford Health',
    'Stanford Health Care',
    'Stanford Health Care - ValleyCare',
    'Starr Regional Medical Center',
    'Staten Island University Hospital',
    'Steward Good Samaritan Medical Center, Inc.',
    'Stillwater Medical Center',
    'StoneSprings Hospital Center',
    'Stonewall Jackson Memorial Hospital',
    'Stony Brook University Hospital',
    'Stormont Vail Health',
    'Straub Clinic & Hospital',
    'Stringfellow Memorial Hospital',
    'Strong Memorial Hospital',
    'Sturdy Memorial Hospital',
    'Suburban Community Hospital',
    'Suburban Hospital',
    'Summa Health System, Akron Campus',
    'Summa Health, Barberton Campus',
    'Summerlin Hospital Medical Center',
    'Summerville Medical Center',
    'Summit Healthcare Regional Medical Center',
    'Sumner Regional Medical Center',
    'Sunrise Hospital and Medical Center',
    'Susan B. Allen Memorial Hospital',
    'Sutter Davis Hospital',
    'Sutter East Bay Hospitals dba Alta Bates Summit Medical Center Alta Bates Campus',
    'Swedish American Hospital',
    'Swedish Edmonds Hospital',
    'Swedish Health Services Issaquah',
    'Swedish Hospital',
    'Swedish Medical Center',
    'Swedish Medical Center Ballard',
    'Swedish Medical Center Cherry Hill',
    'Swedish Medical Center First Hill',
    'Sycamore Shoals Hospital',
    'Syosset Hospital',
    'T. J. Samson Community Hospital',
    'THOMPSON PEAK HOSPITAL',
    'Tacoma General Hospital',
    'Tallahassee Memorial Healthcare',
    'Tampa General Hospital',
    'Tanner Medical Center of Carrollton',
    'Taylor Hospital',
    'Taylor Regional Hospital',
    'Temecula Valley Hospital',
    'Temple University Hospital Jeanes Campus',
    'Tennova Healthcare - Cleveland Main Campus',
    'Tennova Healthcare – Harton',
    'Tennova Healthcare-Clarksville',
    'Terre Haute Regional Hospital',
    'Terrebonne General Medical Center',
    'Texas Health Arlington Memorial Hospital',
    'Texas Health Harris Methodist Hospital Alliance',
    'Texas Health Harris Methodist Hospital Cleburne',
    'Texas Health Harris Methodist Hospital Fort Worth',
    'Texas Health Harris Methodist Hospital Hurst-Euless-Bedford',
    'Texas Health Harris Methodist Hospital Southwest Fort Worth',
    'Texas Health Harris Methodist Hospital Stephenville',
    'Texas Health Huguley Hospital',
    'Texas Health Presbyterian Hospital Dallas',
    'Texas Health Presbyterian Hospital Denton',
    'Texas Health Presbyterian Hospital Flower Mound',
    'Texas Health Presbyterian Hospital Plano',
    'Texas Health Presbyterian Hospital Rockwall',
    'Texas Health Resources Allen',
    'Texoma Medical Center',
    'The Bellevue Hospital',
    'The Brooklyn Hospital Center',
    'The Christ Hospital',
    'The Hospital of Central Connecticut',
    'The Hospitals of Providence - Sierra Campus',
    'The Hospitals of Providence East Campus',
    'The Hospitals of Providence Memorial Campus',
    'The Hospitals of Providence Transmountain Campus',
    'The Johns Hopkins Hospital',
    'The Medical Center of Southeast Texas',
    'The Medical Center, Navicent Health',
    'The Miriam Hospital',
    'The Mount Sinai Hospital',
    'The Ohio State University Hospital East',
    'The Ohio State University Wexner Medical Center',
    'The University of Tennessee Medical Center',
    'The Valley Hospital',
    'The Villages Regional Hospital',
    'The William W. Backus Hospital',
    'Thibodaux Regional Health System',
    'Thomas Hospital',
    'Thomas Jefferson University Hospital',
    'Thomas Jefferson University Hospital - Methodist Hospital Campus',
    'Thomas Memorial Hospital',
    'TidalHealth Nanticoke',
    'TidalHealth Peninsula Regional, Inc.',
    'Tidelands Health Georgetown Memorial Hospital',
    'Tidelands Health Waccamaw Community Hospital',
    'Tift Regional Medical Center',
    'Timpanogos Regional Hospital',
    'Titus County Hospital District dba Titus Regional Medical Center',
    'Tobey Hospital',
    'Torrance Memorial Medical Center',
    'Touro Infirmary',
    'Tri-City Medical Center',
    'TriStar Greenview Regional Hospital',
    'TriStar Southern Hills Medical Center',
    'TriStar StoneCrest Medical Center',
    'TriStar Summit Medical Center',
    'Trident Medical Center',
    'Trinitas Regional Medical Center',
    'Trinity Hospital',
    'Trinity Medical Center West',
    'Trinity Moline',
    'Trinity Rock Island',
    'Trios Southridge Hospital',
    'Tristar Centennial Medical Center',
    'Tristar Hendersonville Medical Center',
    'Tristar Horizon Medical Center',
    'Tristar Skyline Medical Center',
    'Truman Medical Center Hospital Hill',
    'Truman Medical Center Lakewood',
    'Trumbull Memorial Hospital',
    'Tuality Community Hospital',
    'Tuba City Regional Health Care Corporation',
    'Tucson Medical Center',
    'Tufts Medical Center',
    'Tulane Lakeside Hospital',
    'Tulane University Hospital and Clinic',
    'Turkey Creek Medical Center',
    'Twin Cities Community Hospital',
    'Twin Cities Hospital',
    'Twin County Regional Healthcare',
    'U Mass Memorial Medical Center - Memorial Campus',
    'U Mass Memorial Medical Center - University Campus',
    'UAB Highlands',
    'UC San Diego Health Hillcrest - Hillcrest Medical Center',
    'UC San Diego Health La Jolla - Jacobs Medical Center and Sulpizio Cardiovascular Center',
    'UCHealth Longs Peak Hospital',
    'UCHealth Medical Center of the Rockies',
    'UCHealth Memorial Hospital Central',
    'UCHealth Memorial Hospital North',
    'UCHealth Poudre Valley Hospital',
    'UCHealth University of Colorado Hospital',
    'UCHealth Yampa Valley Medical Center',
    'UCLA Medical Center of Santa Monica',
    'UCSF Health - Mission Bay',
    'UCSF Medical Center Moffitt-Long Hospitals',
    'UF Health Jacksonville',
    'UF Health North',
    'UF Health Shands Hospital',
    'UH Cleveland Medical Center',
    'UHS - Binghamton General Hospital',
    'UHS Wilson Medical Center',
    'UK Good Samaritan Hospital',
    'UM Baltimore Washington Medical Center',
    'UM Harford Memorial Hospital',
    'UNC Rockingham Hospital',
    'UNM Sandoval Regional Medical Center',
    'UP Health System - Marquette',
    'UP Health System - Portage',
    'UPMC Altoona',
    'UPMC Carlisle',
    'UPMC Chautauqua',
    'UPMC Community',
    'UPMC East',
    'UPMC Hamot',
    'UPMC Harrisburg',
    'UPMC Horizon - Shenango Valley Campus',
    'UPMC Jameson',
    'UPMC McKeesport',
    'UPMC Mercy',
    'UPMC Northwest',
    'UPMC PASSAVANT',
    'UPMC Passavant - Cranberry',
    'UPMC Pinnacle Hanover',
    'UPMC Pinnacle Lititz',
    'UPMC Pinnacle Memorial',
    'UPMC Presbyterian',
    'UPMC ST MARGARET',
    'UPMC Shadyside',
    'UPMC Somerset',
    'UPMC Susquehanna - Williamsport',
    'UPMC West Shore',
    'UPMC Western Maryland',
    'USC Verdugo Hills Hospital',
    'USMD Hospital at Arlington',
    'UT Health Athens',
    'UT Health Jacksonville',
    'UT Health North Campus Tyler',
    'UT Health Tyler',
    'UT Southwestern Zale Lipshy Pavilion at William P. Clements Jr. University Hospital',
    'UTMB Health Angleton Danbury Campus',
    'UTMB Health League City Campus Hospital',
    'Union General Hospital',
    'Union Hospital',
    'Union Hospital',
    'Uniontown Hospital',
    'United Hospital',
    'United Hospital Center',
    'United Memorial Medical Center',
    'United Memorial Medical Center',
    'United Regional Health Care System',
    'Unity Health Harris Medical Center',
    'Unity Health White County Medical Center',
    'Unity Hospital',
    'UnityPoint Health - Finley Hospital',
    'UnityPoint Health - Meriter',
    'UnityPoint Health - Methodist',
    'UnityPoint Health - Trinity Muscatine',
    'UnityPoint Health - Trinity Regional Medical Center',
    'UnityPoint Health-Pekin',
    'University Health System',
    'University Hospital',
    'University Hospital',
    'University Hospital',
    'University Hospital Summerville',
    'University Hospital and Clinics',
    'University Hospital and Medical Center',
    'University Hospitals Ahuja Medical Center',
    'University Hospitals Bedford Medical Center',
    'University Hospitals Elyria Medical Center',
    'University Hospitals Geauga Medical Center',
    'University Hospitals Parma Medical Center',
    'University Hospitals Portage Medical Center',
    'University Hospitals Richmond Medical Center',
    'University Hospitals Samaritan Medical Center',
    'University Hospitals St. John Medical Center',
    'University Medical Center',
    'University Medical Center New Orleans',
    'University Medical Center of El Paso',
    'University Medical Center of Southern Nevada',
    'University of Alabama Hospital',
    'University of California Davis Medical Center',
    'University of California Irvine Health',
    'University of California Ronald Reagan UCLA Medical Center',
    'University of Chicago Medical Center',
    'University of Cincinnati Medical Center',
    'University of Connecticut Health Center, John Dempsey Hospital',
    'University of Illinois Hospital',
    'University of Iowa Hospitals and Clinics',
    'University of Kansas Health System St Francis Campus',
    'University of Kentucky Albert B. Chandler Hospital',
    'University of Louisville Hospital',
    'University of Maryland Charles Regional Medical Center',
    'University of Maryland Medical Center',
    'University of Maryland Medical Center Midtown Campus',
    'University of Maryland Shore Medical Center at Dorchester',
    'University of Maryland Shore Medical Center at Easton',
    'University of Maryland St. Joseph Medical Center',
    'University of Maryland Upper Chesapeake Medical Center',
    'University of Minnesota Medical Center - West Bank Campus',
    'University of Mississippi Medical Center',
    'University of Mississippi Medical Center Grenada',
    'University of New Mexico Hospital',
    'University of North Carolina Hospitals',
    'University of Texas Medical Branch - Galveston',
    'University of Toledo Medical Center',
    'University of Utah Hospital',
    'University of Vermont Medical Center',
    'University of Virginia Medical Center',
    'University of Washington Medical Center',
    'University of Washington Medical Center Northwest',
    'University of Wisconsin Hospitals and Clinics Authority',
    'UofL Health - Mary & Elizabeth Hospital',
    'Upper Valley Medical Center',
    'Upson Regional Medical Center',
    'Upstate University Hospital - Community Campus',
    'Utah Valley Hospital',
    'VCU Health Community Memorial Hospital',
    'VCU Medical Center Main Hospital',
    'Vail Health',
    'Valley Baptist Medical Center-Brownsville',
    'Valley Baptist Medical Center-Harlingen',
    'Valley Hospital Medical Center',
    'Valley Medical Center',
    'Valley Presbyterian Hospital',
    'Valley Regional Medical Center',
    'Valley View Hospital',
    'Valley View Medical Center',
    'Valleywise Health',
    'Van Wert County Hospital',
    'Vanderbilt University Hospital',
    'Vanderbilt Wilson County Hospital',
    'Vassar Brothers Medical Center',
    'Vaughan Regional Medical Center',
    'Venice Regional Bayfront Health',
    'Verde Valley Medical Center',
    'Via Christi Hospital Manhattan, Inc.',
    'Via Christi Hospital St. Teresa',
    'Via Christi Hospital Wichita, St Joseph',
    'Via Christi Hospitals Wichita - St Francis',
    'Vidant Beaufort Hospital',
    'Vidant Duplin Hospital',
    'Vidant Edgecombe Hospital',
    'Vidant Medical Center',
    'Vidant North Hospital',
    'Vidant Roanoke-Chowan Hospital',
    'Viera Hospital',
    'Virginia Hospital Center--Arlington Health System',
    'Virginia Mason Medical Center',
    'Virginia Mason Memorial',
    'Virtua Marlton Hospital',
    'Virtua Memorial Hospital',
    'Virtua Our Lady of Lourdes Hospital',
    'Virtua Voorhees Hospital',
    'Virtua Willingboro',
    'WK Pierremont Health Center',
    'Wadley Regional Medical Center',
    'Wagoner Community Hospital',
    'Wake Forest Baptist Health High Point Medical Center',
    'Wake Forest Baptist Health Wilkes Medical Center',
    'Wake Forest Baptist Health-Lexington Medical Center',
    'Wake Forest Baptist Medical Center',
    'WakeMed Cary Hospital',
    'WakeMed Raleigh Campus',
    'Walker Baptist Medical',
    'War Memorial Hospital',
    'Warren General Hospital',
    'Washington Hospital',
    'Washington Regional Medical Center',
    'Watauga Medical Center',
    'Watertown Regional Medical Center',
    'Watsonville Community Hospital',
    'Wayne HealthCare',
    'Wayne Memorial Hospital',
    'Wayne UNC Health Care',
    'Weirton Medical Center',
    'Weiss Memorial Hospital',
    'WellSpan Chambersburg Hospital',
    'WellSpan Ephrata Community Hospital',
    'WellSpan Gettysburg Hospital',
    'WellSpan York Hospital',
    'WellStar Spalding Regional Hospital',
    'Wellington Regional Medical Center',
    'Wellspan Good Samaritan Hospital',
    'Wellstar Cobb Hospital',
    'Wellstar Douglas Hospital',
    'Wellstar Kennestone Hospital',
    'Wellstar Paulding Hospital',
    'Wellstar West Georgia Medical Center',
    'Wentworth-Douglass Hospital',
    'Wesley Long Community',
    'Wesley Medical Center',
    'Wesley Woodlawn Hospital & ER',
    'West Anaheim Medical Center',
    'West Boca Medical Center',
    'West Calcasieu Cameron Hospital',
    'West Chester Hospital',
    'West Florida Hospital',
    'West Hills Hospital and Medical Center',
    'West Jefferson Medical Center',
    'West Marion Community Hospital',
    'West Penn Hospital',
    'West Suburban Medical Center',
    'West Valley Medical Center',
    'West Virginia University Hospitals, Inc',
    'Westchester Medical Center',
    'Westerly Hospital',
    'Western Arizona Regional Medical Ctr',
    'Western Missouri Medical Center',
    'Western Plains Medical Complex',
    'Western Reserve Hospital',
    'Westmoreland Hospital',
    'Westside Regional Medical Center',
    'Wheeling Hospital',
    'White Plains Hospital',
    'White River Medical Center',
    'Whitesburg ARH Hospital',
    'Whittier Hospital Medical Center',
    'Wilcox Memorial Hospital',
    'Wilkes-Barre General Hospital',
    'Willamette Valley Medical Ctr',
    'William P. Clements Jr. University Hospital',
    'Williamson Medical Center',
    'Willis-Knighton Bossier Health Center',
    'Wilson Medical Center',
    'Wilson N. Jones Regional Medical Center',
    'Winchester Hospital',
    'Winchester Medical Center',
    'Windham Community Memorial Hospital',
    'Winona Health',
    'Winter Haven Hospital',
    'Wiregrass Medical Center',
    'Wise Health System - East Campus Decatur',
    'Wood County Hospital',
    'Woodland Heights Medical Center',
    'Woodland Memorial Hospital',
    'Woodwinds Health Campus',
    'Wooster Community Hospital',
    'Wyckoff Heights Medical Center',
    'Wyoming Medical Center',
    'Wythe County Community Hospital',
    'YRMC - West',
    'Yale-New Haven Hospital',
    'Yale-New Haven Hospital Saint Raphael Campus',
    'Yavapai Regional Medical Center - East',
    'York Hospital',
    'Yuma Regional Medical Center',
    'Zuckerberg San Francisco General Hospital and Trauma Center',
]



module.exports.images=[
    'http://d279m997dpfwgl.cloudfront.net/wp/2020/04/wide-view-from-above-1000x750.jpg',
    'https://s18671.pcdn.co/wp-content/uploads/2020/05/IMG_1616.jpg',
    'https://www.umms.org/-/media/images/umms/coronavirus/fighting-covid/expanded-locations/overhead-bccfh.jpg?h=310&w=550&la=en&hash=CBB92EB11D714816C2A26FF134759BB9F09CBA4C',
    'https://whyy.org/wp-content/uploads/2021/01/2021-01-08-k-paynter-convention-center-vaccine-opening-5.jpg',
    'https://whyy.org/wp-content/uploads/2021/02/AP_coronavirus_vaccine_philly_convention_center_020721_02.jpg',
    'https://cdn.abcotvs.com/dip/images/10398760_030821-wls-eric-united-center-10p-vid.jpg?w=800&r=16%3A9',
    'https://cdn.abcotvs.com/dip/images/10370782_022521-kgo-sf-moscone-vax-site-img_Image_00-00-25,04.jpg?w=1600',
    'https://kubrick.htvapps.com/htv-prod-media.s3.amazonaws.com/images/baltimore-convention-center-indoor-covid-testing-site-1604678590.png?crop=1.00xw:0.844xh;0,0.0938xh&resize=640:*',
    'https://s.france24.com/media/display/2d6342e2-5acb-11eb-abfc-005056a98db9/w:1280/p:16x9/China%20hebei%20quarantine%20center.webp',
    'https://cdn.abcotvs.com/dip/images/10362968_022221-kgo-moscone-center-inside-img_Image_00-00-14,23.jpg?w=800&r=16%3A9',
    'https://www.orlandosentinel.com/resizer/hrSNF4sOUzfhR2uYzkMcyPN8aNY=/415x240/top/cloudfront-us-east-1.images.arcpublishing.com/tronc/N5V2YIJNHFDMBMDY6A3XCRNK54.jpg',
    'https://ghwcc.org/wp-content/uploads/2019/01/HOSH-Cover-scaled.jpg',
    'https://images.squarespace-cdn.com/content/v1/567acee20ab377f38f7f0c72/1553196508664-Y8MA0TB38H5ZKHI12H7W/ke17ZwdGBToddI8pDm48kG87Sfbgg29A4BYEDq3OXvgUqsxRUqqbr1mOJYKfIPR7LoDQ9mXPOjoJoqy81S2I8N_N4V1vUb5AoIIIbLZhVYxCRW4BPu10St3TBAUQYVKcf4OxbJOyh_wHUnyc4kQLQ6SBshRGOku7c30Y_IRDNPta8R2IY5BHMaEj1zOWoDTZ/01-Lone-Peak-Medical-Office-Building-And-Lone-Peak-Surgery-Center-Draper-UT-min.jpg?format=750w',
    'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4QOYTTKmpNR9NNZXMDls5SwqB-Ovy8fgvzQ&usqp=CAU',
    'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8aG9zcGl0YWx8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',
    'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?ixid=MXwxMjA3fDB8MHxzZWFyY2h8Mnx8aG9zcGl0YWwlMjBidWlsZGluZ3xlbnwwfHwwfA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60m',
    'https://images.unsplash.com/photo-1587351021250-2aeafcc4c6c2?ixid=MXwxMjA3fDB8MHxzZWFyY2h8MTF8fGhvc3BpdGFsJTIwYnVpbGRpbmd8ZW58MHx8MHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60',

]